/*
 * can_helper.c
 *
 *  Created on: Mar 21, 2025
 *      Author: ella
 *      Description: CAN helper files. Not including CAN setup/initialization/autogenerated code as to not mess with cubemx.

*/

#include "can_helper.h"
#include "main.h"
#include "config.h"
#include <stdio.h>
#include <string.h>

volatile uint8_t can_message_ready = 0;
uint8_t last_rx_data[8];
uint32_t last_rx_id;

extern CAN_HandleTypeDef hcan;


void HAL_CAN_RxFifo0MsgPendingCallback(CAN_HandleTypeDef *hcan) {
	//printf("🎯 Callback hit!\r\n");
	CAN_RxHeaderTypeDef rx_header; //Stores the header information of the msg (e.g., message ID, length, format).
	uint8_t rx_data[8]; //Array to store the 8 bytes of data from the received CAN message.

	if (HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &rx_header, rx_data) == HAL_OK){
		memcpy((void *)last_rx_data, rx_data, 8);
		last_rx_id = rx_header.StdId;
		can_message_ready = 1;
	}
}


void send_can_message(uint8_t txData[8]) {
    CAN_TxHeaderTypeDef tx_header;
    uint32_t tx_mailbox;

    tx_header.StdId = AIRSPEED_CAN_ID;
    tx_header.ExtId = AIRSPEED_CAN_ID; // This is ignored, we are using STD IDs
    tx_header.IDE = CAN_ID_STD;
    tx_header.RTR = CAN_RTR_DATA;
    tx_header.DLC = 8;
    tx_header.TransmitGlobalTime = DISABLE;

    if (HAL_CAN_AddTxMessage(&hcan, &tx_header, txData, &tx_mailbox) != HAL_OK){
        printf("❌ CAN TX failed\r\n");
    } else {
        printf("✅ CAN Message Sent!\r\n");
    }
}


void print_last_rx(void){
    if (can_message_ready){
        printf("📥 Received CAN ID: 0x%X, Data: ", last_rx_id);
        for (int i = 0; i < 8; i++)
        {
            printf("%02X ", last_rx_data[i]);
        }
        printf("\r\n");
    } else {
    	printf("No Messages Received Yet\r\n");
    }
}

